//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public ChiTietPhieuXuat(string mapx, string masp, int soluong, double thanhtien)
        {
            Mapx = mapx;
            Masp = masp;
            Soluong = soluong;
            ThanhTien = thanhtien;
        }

        public string Mapx { get; set; }
        public string Masp { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
